spring.application.name=apitest

spring.config.import=optional:application-secret.properties

#spring.ai.openai.api-key={secret-openAiKey}
openai.api-key=${secret-openAiKey}

uCanSignKey=${secret-uCanSignKey}





server.port=8080